### ISSUE TITLE
jpeg62.dll missing for Win 10 installation

### ISSUE THREAD

**Issue by Svendergrosse** [dannyedel/dspdfviewer#213]
Hi Danny and Dspdf team,

in the latest release 1.15.1.3, a dll seems to be missing for the Windows installation: jpeg62.dll.

please see attached screenshot. 

PS. all previous versions run sucessfully on my win 10 platform

![Capture](https://user-images.githubusercontent.com/6673512/73608744-72c77b00-45be-11ea-8f9d-4ee6a3febee2.PNG)

**Comment by projekter** [comment]
Indeed, as I said in the release comment, I for the first time activated the better turbojpeg driver; however, since it was compiled statically, it _should_ not require any DLL. While I investigate this issue, the attached DLL should temporarily fix the issue.

[jpeg62.zip](https://github.com/dannyedel/dspdfviewer/files/4144212/jpeg62.zip)

**Comment by projekter** [comment]
Ok, can you please try the attached file (without the `jpeg62.dll` that I gave before)? Apparently, Qt somehow configured itself to use the shared libraries. I still need to look for an `official` way to change this, at the moment I hard-rewrote some dependencies. The jpeg testcase did still work properly.

[dspdfviewer.zip](https://github.com/dannyedel/dspdfviewer/files/4144559/dspdfviewer.zip)

**Comment by projekter** [comment]
I now turned this into a new release.
