### ISSUE TITLE
Long time no update? Alternative?

### ISSUE THREAD

**Issue by MartinX3** [dannyedel/dspdfviewer#214]
Should be worry about that this project wasn't updated since 2016 (security issues, etc)?
Is there a good alternative to view LaTeX presentations with their page comments?
Yes, there is one!
https://github.com/pdfpc/pdfpc/
It uses a different approach to add the notes but for the CTAN package `pdfpc` it works almost the same in LaTeX.
https://github.com/pdfpc/pdfpc/issues/472 -> Removed the beamer notes
The different approach is described here
https://github.com/pdfpc/pdfpc/pull/471

**Comment by einhander** [comment]
https://github.com/pdfpc/pdfpc/ -linux only, windows support is limited.

**Comment by dannyedel** [comment]
Hello Martin and einhander,

I apologize for not updating this in a long while -- I have been busy with lots of other things in real life.

Regarding security issues: I have not been made aware of any, at least not yet ; )

----

I'll close this ticket for now, since there is nothing to do here really.
