### ISSUE TITLE
Allow for links

### ISSUE THREAD

**Issue by projekter** [dannyedel/dspdfviewer#35]
It would be great if support for links in the PDF is added. All the nice navigations created with beamer tend to be useless if they are not interactive, so that one can jump to another page if it becomes necessary in a talk.
By the way, compilation under Windows worked well; I can provide a binary if you wish to integrate it.

**Comment by dannyedel** [comment]
I agree, PDF Link support would be great. I've actually looked into that a few months ago, I think I can get that running.

Because I have not done any presentations in a while, there has been little work on dspdfviewer, and I currently don't have any presentations whose links do more than "ahead 1 page / back 1 page".

If you want to help me on this, you would do me a huge favor if you created a dualscreen PDF that contains the kind of hyperlinks you normally use, so I can try to get that running. Hosting it in a gist and throwing a link at the ticket here would be best.

---- snip ----

Running on Windows: If you could edit (pull-request) the [README.md] to add a section on how you compiled it under Windows, that would be great. If you have ready-made binaries to download, please add a link to them, with a comment such as "binaries provided by (your name)" 

[README.md]: https://github.com/dannyedel/dspdfviewer/blob/master/README.md

**Comment by projekter** [comment]
Sure, [PDF](https://www.dropbox.com/s/j7cepuf3vc393qq/test.pdf?dl=0) and [Gist TeX source](https://gist.github.com/projekter/d111bbe87003b1f660da) file. Normally, I don't use this kind of navigation but the sidebar navigation provided by Hannover theme. But it is a bit harder to make this work in dual screen mode, I'm still working on it. The example file in in its essence taken from [this SO question](http://tex.stackexchange.com/questions/232838/beamer-with-notes-on-the-left-have-navigation-links-working-both-on-slides-rig).

**Comment by dannyedel** [comment]
Since PR #37 is merged, all that remains is the "running on windows" part and then the ticket is cleared.

**Comment by dannyedel** [comment]
Running on windows is now discussed in #38 so this ticket is done.
